apiVersion: v1
kind: ConfigMap
metadata:
  name: backend-config
  data:
    DB_HOST: database-1.c2pkkgg0mxb2.us-east-1.rds.amazonaws.com
      DB_NAME: book_review_db
        DB_USER: admin
          DB_DIALECT: mysql
            PORT: "3001"
              ALLOWED_ORIGINS: http://a20ada6ee9b704aefafd3f7b49dd34a4-1667481319.us-east-1.elb.amazonaws.com
              
